# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mTZpv_JltCPzW_MFikPNZvyD2uJtHi5M
"""

# build my own data type that is : Fracton

class Fraction:

  def __init__(self,x,y):
    self.num=x
    self.den=y

  def __str__(self):
   return '{}/{}'.format(self.num,self.den)

  def __add__(self,other):
    new_num=self.num*other.den+other.num*self.den
    new_den=self.den*other.den

    return '{}/{}'.format(new_num,new_den)

  def __sub__(self,other):
    new_num=self.num*other.den - other.num*self.den
    new_den=self.den*other.den

    return '{}/{}'.format(new_num,new_den)

  def __mul__(self,other):
    new_num=self.num*other.num
    new_den=self.den*other.den

    return '{}/{}'.format(new_num,new_den)


  def __truediv__(self,other):
    new_num=self.num*other.den
    new_den=self.den*other.num

    return '{}/{}'.format(new_num,new_den)

Fr1 = Fraction(3,4)
Fr2= Fraction(5,6)

print(Fr1*Fr2)
print(Fr1/Fr2)
print(Fr1+Fr2)
print(Fr1-Fr2)